### ISSUE TITLE
Releases are JS versions

### ISSUE THREAD

**Issue by leebenson** [reactql/kit.ts#18]
@jtmthf - looking at https://github.com/reactql/kit.ts/releases, it seems the .zip for each reflect the JS versions of the kit.

I noticed when bumping the TS version via the CLI this morning (not yet committed; just locally).

Not sure if that's an artefact of how merging is being handled?

**Comment by nisimjoseph** [comment]
any update about this one?

**Comment by leebenson** [comment]
Given that all versions of the TS kit seem affected by this, I'll disable Typescript support in the next release of the CLI to avoid confusion. Will put it back once this is fixed.

**Comment by leebenson** [comment]
@jtmthf - I appreciate you taking the time to maintain the TS version of the kit. I've currently removed support from the CLI due to this issue; it seems that no matter which flavour was selected, users ultimately got the JS version, so I've temporarily pulled that option until there's a fix.

Given that the kit is now several versions behind, I'm not sure how you want to play the merge strategy. I appreciate that each kit change adds extra work on your plate, so I'm mindful of putting something in place that is manageable.

**Comment by saulba** [comment]
Very nice kit. Yet it's a bit lagging behind js kit. I just thought to try to convert latest js kit to ts, but just stumbled at converting server_prod.js to ts:
`router.get('/*', createReactHandler(css, scripts, chunkManifest));`  with `scripts` parameter error `
severity: 'Error'
message: 'Argument of type 'any[]' is not assignable to parameter of type 'never[] | undefined'.
  Type 'any[]' is not assignable to type 'never[]'.
    Type 'any' is not assignable to type 'never'.'
at: '53,44'
source: 'ts'`

It seems at server.js `css` and `scripts` both are an arrays and at server_prod they are arrays.

At server_dev `createReactHandler(css, scripts)` parameters are failing too though css there is a string. And in previous version `createReactHandler`  pars `(css, scripts)` was just a nullable strings.

Can you take a look at it so how to fit them? Thanks.

**Comment by leebenson** [comment]
@saulba - the Typescript version is currently around 12 versions behind the kit ([version bumps](https://github.com/reactql/kit.ts/issues) are being tracked).

The TS version is maintained by @jtmthf, so I'd defer to his suggestions. I'm not a Typescript user myself, so I'm not intimately familiar with what might need changing.

I disabled Typescript support in the [CLI](https://github.com/reactql/cli) a couple of weeks ago to avoid confusion. I'll re-enable support as soon as there's a working PR/release.

**Comment by saulba** [comment]
@leebenson - ok. Cool. I will use current ts version with minor changes to make it workable and wait for @jtmthf . Thanks for nice kit once again.

**Comment by jtmthf** [comment]
@leebenson @saulba Sorry for being out for so long. I recently moved and started a new job which has been consuming my time. Things are starting to settle down now and I spent some time today getting this kit back up to date.

It appears that I had the wrong approach to updating earlier by merging in the latest kit changes whether or not I had missed a few versions in-between. What I found to work better is to only merge in one version of the kit at a time and then release those changes. The merge conflicts tend to be significantly smaller and once I overwrite the tag, the releases page has the correct version.

So far I've pushed 1.4.0 and 1.4.1 which are now tagged correctly. Over the weekend I'll work on getting more of the kit up to date so that it may be brought back into the CLI.

**Comment by leebenson** [comment]
Thanks @jtmthf, appreciate your time on this. And congrats on the new job!

**Comment by saulba** [comment]
@jtmthf great to hear you are back. And yea, congrats and all the best :)

**Comment by tzarger** [comment]
@jtmthf First off, congrats on the new gig!
Thanks for your efforts to update this kit so we can use Typescript. I see you made some additional progress and was wondering when you might have a change to finish getting back up to date so we can get the TS kit back online in the CLI. I am starting a new project and would love to use this kit. Thanks a bunch for all your efforts!

**Comment by tzarger** [comment]
@jtmthf Hello Jack, again, congrats on the new job! With all that you have going on, are you going to have any time soon to work on getting this kit updated?

**Comment by leebenson** [comment]
Given that this thread is now a couple of months old, and I'm regularly being asked why the TS version isn't working, I'm going to remove official TS support from the documentation for now so users aren't confused by the option not being there on the CLI.

If TS support catches up to the kit, then I'll re-enable at that time. However, we'd need to figure out a way to prevent it falling behind in future, otherwise it'll remain out of sync, which makes it very hard to release consistent documentation.

**Comment by leebenson** [comment]
FYI, [v2.0](https://github.com/reactql/kit/releases/tag/2.0.0) of the ES6 kit has been released, which introduces many changes - including enhanced configurability of the kit in userland code, and an (optional) built-in GraphQL server for running a full-stack app.

As such, the Typescript variant is now very much behind, and isn't being actively maintained.

I have officially deprecated the Typescript version and removed mention of a TS version in the [docs](https://reactql.org/docs) and the CLI tool.

I will leave this project open for legacy reasons. However, at this time, I do not expect any further updates to be made. It takes a lot of time to maintain a separate flavour of the kit, and is very easy to fall out of sync with a fast-moving project.

I wish to thank @jtmthf for his time on maintaining this version of the kit -- much appreciated, and good luck in the new role!

**Comment by pie6k** [comment]
Thats sad. Lack of active typescript support is one and the only reason I'm not using it for my project.

**Comment by leebenson** [comment]
I'm working on a modular framework as a successor to ReactQL, that should make it possible to reintroduce Typescript support relatively simply.

Will keep you posted.

**Comment by younanjo** [comment]
@leebenson any progress of the framework?

**Comment by leebenson** [comment]
Should have some news in a few days. Actively working on it.
