### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by zunder** [reactql/kit.ts#25]
Out of curiosity, is there any React Native support planned in near future?

**Comment by jtmthf** [comment]
That's a good question, but it might be better aimed at the base reactql/kit project. The majority of the work in this project is webpack configuration which isn't relevant to React Native. Some of the only things that would apply to React Native are the Redux, Apollo, and Eslint which would be easy to copy over.

Now if you're maybe interested in a hybrid application in which you have a single code-base for both web and native, there's some interesting work there, but I don't think any of it is ready for primetime yet. Microsoft has their ReactXP project and react-primitives has also made some groundwork as well. Likely an even better solution will emerge in the future that will make it easier to share a web and native code base.
